winget install 7zip
winget install gnupg
winget install gpg4win
winget install powertoys
winget install Clink
winget install gow
winget install googlechrome
winget install -i vscode
winget install docker
winget install steam
winget install discord
winget install vlc
winget install sumatrapdf
winget install slack
winget install obs
winget install screentogif
winget install crystaldiskinfo
winget install coretemp
winget install DeepL.DeepL
winget install nomacs.nomacs
winget install Mozilla.Thunderbird
winget install MehediHassan.Tweeten
winget install LINE.LINE
winget install Peppy.Osu!
winget install Microsoft.WindowsTerminal
winget install Amazon.Music
winget install Google.ChromeRemoteDesktop
winget install Kitware.CMake
winget install ALCPU.CoreTemp
winget install -e --id flux.flux
winget install KiCad.KiCad
winget install Mattermost.MattermostDesktop
winget install Kuro.Mery
winget install TeamViewer.TeamViewer
winget install File-New-Project.EarTrumpet
